/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import java.util.List;
import model.AlgoritmoGenetico;
import model.Grafico;
import model.Individuo;
import model.Lista;
import model.Produto;
import org.jfree.ui.RefineryUtilities;
import runner.Arquivo;

/**
 *
 * @author Lucas
 */
public class Menu extends javax.swing.JFrame {

    private static AlgoritmoGenetico algoritmoGenetico;
    private static MelhorSolucao melhorSolucao;
    private static MelhoresIndividuos melhoresIndividuos;
    private List<Individuo> individuos;
    private static String textoMelhoresIndividuos;
    private static String textoMelhorSolucao;
   

   
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
     
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botaoMelhoresIndividuos = new javax.swing.JButton();
        botaoGrafico = new javax.swing.JButton();
        botaoMelhorSolucao = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoDeTextoTamanhoDaPopulacao = new javax.swing.JTextField();
        campoDeTextoNumeroDeGeracoes = new javax.swing.JTextField();
        campoDeTextoTaxaDeMutacao = new javax.swing.JTextField();
        CampoDeTextoLimiteDeEspaco = new javax.swing.JTextField();
        botaoAtribuir = new javax.swing.JButton();

        jButton3.setText("jButton1");

        jButton5.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(105, 105, 105));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Algoritmo Genético");

        botaoMelhoresIndividuos.setBackground(new java.awt.Color(88, 101, 242));
        botaoMelhoresIndividuos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoMelhoresIndividuos.setForeground(new java.awt.Color(255, 255, 255));
        botaoMelhoresIndividuos.setText(" Melhores Individuos");
        botaoMelhoresIndividuos.setBorder(null);
        botaoMelhoresIndividuos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMelhoresIndividuosActionPerformed(evt);
            }
        });

        botaoGrafico.setBackground(new java.awt.Color(88, 101, 242));
        botaoGrafico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoGrafico.setForeground(new java.awt.Color(255, 255, 255));
        botaoGrafico.setText("Gráfico");
        botaoGrafico.setBorder(null);
        botaoGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGraficoActionPerformed(evt);
            }
        });

        botaoMelhorSolucao.setBackground(new java.awt.Color(88, 101, 242));
        botaoMelhorSolucao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoMelhorSolucao.setForeground(new java.awt.Color(255, 255, 255));
        botaoMelhorSolucao.setText("Melhor Solução");
        botaoMelhorSolucao.setBorder(null);
        botaoMelhorSolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMelhorSolucaoActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(105, 105, 105));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Entradas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setToolTipText("ggggggg");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tamanho da população:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Número de gerações:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Taxa de mutação:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Limite de espaço:");

        campoDeTextoTamanhoDaPopulacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDeTextoTamanhoDaPopulacaoActionPerformed(evt);
            }
        });

        campoDeTextoNumeroDeGeracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDeTextoNumeroDeGeracoesActionPerformed(evt);
            }
        });

        campoDeTextoTaxaDeMutacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDeTextoTaxaDeMutacaoActionPerformed(evt);
            }
        });

        botaoAtribuir.setBackground(new java.awt.Color(88, 101, 242));
        botaoAtribuir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoAtribuir.setForeground(new java.awt.Color(255, 255, 255));
        botaoAtribuir.setText("Calcular");
        botaoAtribuir.setBorder(null);
        botaoAtribuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtribuirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(botaoAtribuir, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CampoDeTextoLimiteDeEspaco, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoDeTextoTaxaDeMutacao, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(campoDeTextoNumeroDeGeracoes, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                .addComponent(campoDeTextoTamanhoDaPopulacao)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoDeTextoTamanhoDaPopulacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(campoDeTextoNumeroDeGeracoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(campoDeTextoTaxaDeMutacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CampoDeTextoLimiteDeEspaco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(botaoAtribuir, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoMelhorSolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoMelhoresIndividuos, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(botaoMelhoresIndividuos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoMelhorSolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoDeTextoTamanhoDaPopulacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDeTextoTamanhoDaPopulacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDeTextoTamanhoDaPopulacaoActionPerformed

    private void campoDeTextoTaxaDeMutacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDeTextoTaxaDeMutacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDeTextoTaxaDeMutacaoActionPerformed

    private void botaoGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGraficoActionPerformed
      Grafico grafico = new Grafico("Algoritmo genético","Evolução das soluções",individuos);
      grafico.pack();
      RefineryUtilities.centerFrameOnScreen(grafico);
      grafico.setVisible(rootPaneCheckingEnabled);
      
    }//GEN-LAST:event_botaoGraficoActionPerformed

    private void botaoAtribuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtribuirActionPerformed
 //cria a lista com produtos
      List<Produto> listaProdutos = Arquivo.criaListaDeProdutos();
    //preenche o atributo lista
    Lista lista = new Lista(listaProdutos);
    
     algoritmoGenetico = new AlgoritmoGenetico(Integer.parseInt(this.campoDeTextoTamanhoDaPopulacao.getText()));
     List<String> textos = algoritmoGenetico.resolver(Double.parseDouble(this.campoDeTextoTaxaDeMutacao.getText()), Integer.parseInt(this.campoDeTextoNumeroDeGeracoes.getText()), Double.parseDouble(this.CampoDeTextoLimiteDeEspaco.getText()), lista);
     textoMelhoresIndividuos = textos.get(1);
     textoMelhorSolucao = textos.get(0);
     individuos = new ArrayList<Individuo>();
     individuos = algoritmoGenetico.getMelhores();
     
    }//GEN-LAST:event_botaoAtribuirActionPerformed

    private void botaoMelhoresIndividuosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMelhoresIndividuosActionPerformed
        this.melhoresIndividuos = new MelhoresIndividuos();
        melhoresIndividuos.adicionaTexto(textoMelhoresIndividuos);
        //melhoresIndividuos.enable(true);
        melhoresIndividuos.setVisible(true);
       
    }//GEN-LAST:event_botaoMelhoresIndividuosActionPerformed

    private void botaoMelhorSolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMelhorSolucaoActionPerformed
         this.melhorSolucao = new MelhorSolucao();
         melhorSolucao.adicionaTexto(textoMelhorSolucao);
        melhorSolucao.setVisible(true);
    }//GEN-LAST:event_botaoMelhorSolucaoActionPerformed

    private void campoDeTextoNumeroDeGeracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDeTextoNumeroDeGeracoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDeTextoNumeroDeGeracoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
          //cria a lista com produtos
   
   
     
   
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoDeTextoLimiteDeEspaco;
    private javax.swing.JButton botaoAtribuir;
    private javax.swing.JButton botaoGrafico;
    private javax.swing.JButton botaoMelhorSolucao;
    private javax.swing.JButton botaoMelhoresIndividuos;
    private javax.swing.JTextField campoDeTextoNumeroDeGeracoes;
    private javax.swing.JTextField campoDeTextoTamanhoDaPopulacao;
    private javax.swing.JTextField campoDeTextoTaxaDeMutacao;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
